apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-tcp
spec:
  ports:
  - name: "tcp"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: auth
  type: ClusterIP
status:
