services:
  e2e:
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
  reservations:
    image: asia-southeast1-docker.pkg.dev/ageless-airship-404212/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  payments:
    image: asia-southeast1-docker.pkg.dev/ageless-airship-404212/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
  notifications:
    image: asia-southeast1-docker.pkg.dev/ageless-airship-404212/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
  auth:
    image: asia-southeast1-docker.pkg.dev/ageless-airship-404212/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  mongo:
    image: mongo
    ports:
      - '28017:27017'